/* ---------------- THE TWELVE ----------------
   Every subject is a real figure from the vault's Source Library, named on
   each sheet so the drawing can be checked against its source. Where a
   figure carried callout labels and leader lines, a clean photograph or
   clean cutaway of the same product was used instead - cropping around
   callouts was leaving arrow stubs in frame.

   Specifications are the standard published figures for the family, not
   size-by-size datasheet values. Each sheet says so. */
const YEAR = 2027;

const MONTHS = [
  { m:0, art:'a657', back:'beach',
    model:'Fisher 657', size:'Size 80 · on an NPS 4 EH',
    sub:'Spring-and-Diaphragm Actuator', fig:'CVS O&G fig 11-3',
    cap:'She has been pushing down to close since before you were born, and she will still be doing it after you retire.',
    vitals:[['Action','Direct — air loads the casing, stem goes down'],
            ['Bench set','Commonly 6 – 15 psig'],
            ['Shown on','NPS 4 EH/HP body'],
            ['Instrument','FIELDVUE DVC6010'],
            ['Fail','Stem up on loss of air'],
            ['Casing','Pressed steel, bolted rim']],
    on:'Clean, dry instrument air. A positioner that actually listens.',
    off:'Being called “just the actuator.” Packing nobody thought to adjust.' },

  { m:1, art:'a667', back:'alpine',
    model:'Fisher 667', size:'HP Control Valve',
    sub:'Spring-and-Diaphragm, Reverse', fig:'CVS O&G fig 8-11',
    cap:'Her sister gets the attention. She does the same work in the opposite direction and has never once mentioned it.',
    vitals:[['Action','Reverse — air loads the casing, stem goes up'],
            ['Spring','In the yoke, below the diaphragm'],
            ['Body','HP, forged, CL1500'],
            ['Fail','Stem down on loss of air'],
            ['Bench set','Commonly 6 – 15 psig'],
            ['Twin','657, and she is aware']],
    on:'A duty that needs fail-closed and a straight answer about why.',
    off:'Being specified by someone who meant to write 657.' },

  { m:2, art:'v150', back:'mill',
    model:'Fisher Vee-Ball V150', size:'NPS 3 · 2052 · DVC6200',
    sub:'Segmented Ball, Rotary', fig:'CVS O&G fig 11-8',
    cap:'The curve on that notch is not decoration. Every degree of it was put there to shape the flow.',
    vitals:[['Rotation','90°'],['Characteristic','≈ equal percentage'],
            ['Actuator','2052 spring-and-diaphragm, size 1'],
            ['Instrument','FIELDVUE DVC6200'],
            ['Shaft','Splined, through a bolted packing box'],
            ['Service','Slurry, pulp stock, fibrous']],
    on:'Stock that would seize anything else. Being credited for the notch.',
    off:'People who glance at her and say “oh, a ball valve.”' },

  { m:3, art:'et', back:'poolside',
    model:'Fisher Large ET', size:'Drilled-Hole Cage',
    sub:'Globe Body, Balanced Plug', fig:'CVS O&G fig 1-3',
    cap:'She splits the flow into a hundred small streams on the way through, and the spacing of those holes is not a guess.',
    vitals:[['Body','Globe, flanged, large'],
            ['Trim','Cage-guided, balanced plug'],
            ['Cage','Drilled hole, for noise attenuation'],
            ['Hole spacing','Controlled, to stop jets interacting'],
            ['Benefit','Lower plug force, smaller actuator'],
            ['Trim change','In line, without unbolting the body']],
    on:'A clean cage. Trim sized for the duty that actually exists.',
    off:'Being bought two sizes large “for future expansion.”' },

  { m:4, art:'b8560', back:'desert',
    model:'Fisher 8580', size:'With 2052 · DVC6000',
    sub:'High-Performance Butterfly', fig:'CVS O&G fig 11-6',
    cap:'All disc and no apologies. Tight shutoff, high capacity, and she takes up almost nothing in your line.',
    vitals:[['Style','High-performance, offset disc'],['Rotation','90°'],
            ['Actuator','2052 spring-and-diaphragm'],
            ['Instrument','FIELDVUE DVC6000'],
            ['Shutoff','Tight, via the seal ring'],
            ['Face-to-face','Barely there']],
    on:'A long straight run upstream and nobody crowding her with an elbow.',
    off:'Being asked to throttle at eight degrees open, forever.' },

  { m:5, art:'baumann', back:'loch',
    model:'Baumann 24000', size:'NPS 1 · “Little Scotty”',
    sub:'Size 32 Actuator + DVC6200', fig:'CVS O&G fig 1-5',
    cap:'They call her Little Scotty. She is the size of a kettle, she runs the whole sample line, and she has her own instrument.',
    vitals:[['Size','NPS 1, and that is plenty'],['Body','Screwed or flanged'],
            ['Actuator','Size 32 spring-and-diaphragm'],
            ['Instrument','FIELDVUE DVC6200'],
            ['Footprint','Smaller than the bracket you will build for it'],
            ['Nickname','Earned']],
    on:'Being taken seriously in spite of the handle on the name.',
    off:'Being left off the equipment list because she looked like a fitting.' },

  { m:6, art:'dvc', back:'city',
    model:'FIELDVUE DVC6200', size:'Digital',
    sub:'Digital Valve Controller', fig:'CVS O&G fig 2-12',
    cap:'It is not that she is complicated. It is that she has rather more to say than four to twenty milliamps allows.',
    vitals:[['Input','4 – 20 mA, HART'],['Feedback','Non-contact, linkage-less'],
            ['Diagnostics','Valve signature, partial stroke'],
            ['Mounting','Integral or remote'],
            ['Gauges','Supply and output, both'],
            ['Opinions','Numerous, and all logged']],
    on:'A clean valve signature. Somebody who runs the partial stroke test.',
    off:'Being commissioned by guesswork, then blamed for the result.' },

  { m:7, art:'v500', back:'terminal',
    model:'Fisher 1061', size:'Double-Acting',
    sub:'Pneumatic Piston Rotary Actuator', fig:'CVS O&G fig 2-4',
    cap:'When the diaphragm is simply not going to make the torque, this is who they call, and she does not need asking twice.',
    vitals:[['Type','Pneumatic piston, rotary'],['Action','Double acting'],
            ['Rotation','Up to 90°'],
            ['Supply','Higher than a diaphragm would want'],
            ['Torque','Considerably more'],
            ['Pairs with','Large butterfly and ball valves']],
    on:'A big disc that nothing else in the catalogue will shift.',
    off:'A supply header that sags the moment she strokes.' },

  { m:8, art:'whisperflo', back:'forest',
    model:'Fisher WhisperFlo', size:'ET CL300 · Spoked Plug',
    sub:'Aerodynamic Noise Attenuation', fig:'CVS O&G fig 10-5',
    cap:'She will pass the same gas as anyone else in this calendar, and you will struggle to hear her do it.',
    vitals:[['Purpose','Aerodynamic noise attenuation'],
            ['Method','Many small passages, staged expansion'],
            ['Trim','Spoked plug, fluted cage'],
            ['Body','ET, ASME CL300'],
            ['Service','Compressible flow, high pressure drop'],
            ['Volume','Indoor']],
    on:'A gas letdown and a noise limit somebody intends to honour.',
    off:'Being value-engineered out in March and missed at startup in October.' },

  { m:9, art:'notchflo', back:'rapids',
    model:'Fisher NotchFlo DST', size:'Trim',
    sub:'Staged Pressure Drop', fig:'CVS O&G fig 12-5',
    cap:'She takes the pressure drop in stages, so that your valve body does not have to take all of it in one place.',
    vitals:[['Purpose','Cavitation and erosion control'],
            ['Method','Staged drop through notched disks'],
            ['Service','High pressure drop liquid'],
            ['Typical','Water injection, brine disposal'],
            ['Trim','Stacked, notched'],
            ['Patience','Finite']],
    on:'Being specified before the damage rather than after the failure report.',
    off:'Being fitted to a body already washed out behind the seat.' },

  { m:10, art:'ehd', back:'powerhouse',
    model:'Fisher EHD', size:'ASME CL2500',
    sub:'High-Pressure Globe', fig:'CVS O&G fig 1-4',
    cap:'Two thousand five hundred pound class. She throttles high-pressure steam all day and declines to discuss it.',
    vitals:[['Rating','ASME CL2500'],
            ['Service','High-pressure steam and liquid'],
            ['Body','Heavy, stepped, flanged'],
            ['Bonnet','Studded, with a second bolted joint below'],
            ['Trim','Anti-noise and anti-cavitation available'],
            ['Mass','Bring the right lifting gear']],
    on:'A properly engineered support and nobody standing on her.',
    off:'Being hand-tightened. Being lifted by the stem.' },

  { m:11, art:'v250', back:'subsea',
    model:'Fisher A31A', size:'Cryogenic',
    sub:'Butterfly, Extended Bonnet', fig:'CVS O&G fig 14-3',
    cap:'Minus one hundred and sixty degrees, and the only one on this bench who was built for December on purpose.',
    vitals:[['Service','Cryogenic — LNG and cold liquids'],
            ['Bonnet','Extended, to keep packing warm'],
            ['Style','High-performance butterfly'],
            ['Rotation','90°'],
            ['Materials','Selected for low temperature'],
            ['Comfort zone','Well below yours']],
    on:'A long extension bonnet and somebody who understands why it is there.',
    off:'Being insulated so enthusiastically that the packing freezes anyway.' },
];
